# Copyright 2026 Samsarix LLC and contributors.
# SPDX-License-Identifier: MPL-2.0

"""Exercise generate/edit/resume/evaluate offline; all writing and scores are fixtures."""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from pathlib import Path

from samsarix_narrative_engine import (
    EvaluationCase,
    EvaluationManifest,
    EvaluationTreatment,
    Message,
    ProviderResponse,
    RubricCriterion,
    dumps_run_bundle,
    load_run_bundle,
    loads_run_bundle,
)
from samsarix_narrative_engine.cli import main as narrative_cli

BRIEF = (
    "Design a non-combat harbor signal quest for one keeper and one player. "
    "A failed signal must be retryable without consuming the brass bell. "
    "No engine integration is available; deliver a Markdown implementation packet."
)
CORRECTION = (
    "Human edit: on failed signal set signal_ready=false, keep bell_owned=true, "
    "and return to the keeper for another attempt. On success set harbor_warned=true."
)
BASELINE = """# Harbor Signal — OFFLINE FIXTURE
1. Keeper asks the player to ring the brass bell.
2. Player rings the bell; the harbor is warned if the signal succeeds.
Open question: what happens when the signal fails?
This canned packet is not generated by a model or integrated with a game engine.
"""
REVISED = """# Harbor Signal — OFFLINE FIXTURE
1. Keeper lends the bell: set bell_owned=true and signal_ready=true.
2. Player chooses to signal or return to the keeper.
3. Signal success: set harbor_warned=true; keeper acknowledges completion.
4. Signal failure: set signal_ready=false; keep bell_owned=true.
5. Returning after failure resets signal_ready=true and allows another attempt.
Open production question: which game event reports signal success?
This canned packet demonstrates an edited retry path, not a tested game integration.
"""


class FixtureProvider:
    """Inject fixed responses through the real CLI; never connect to a provider."""

    name = "offline-fixture"

    def __init__(self, responses: Sequence[str], required_context: str = "") -> None:
        self.responses = list(responses)
        self.required_context = required_context
        self.calls = 0

    async def complete(
        self, messages: Sequence[Message], *, max_output_tokens: int
    ) -> ProviderResponse:
        if self.required_context and self.required_context not in messages[-1].content:
            raise RuntimeError("the resumed request did not receive the human edit")
        if not self.responses or max_output_tokens <= 0:
            raise RuntimeError("unexpected fixture request")
        self.calls += 1
        return ProviderResponse(
            content=self.responses.pop(0), provider=self.name, model="canned-text-v1"
        )  # Usage stays unreported: this demo has no model tokens or API cost.


def _cli(arguments: Sequence[str], provider: FixtureProvider | None = None) -> None:
    if provider is None:
        code = narrative_cli(arguments)
    else:
        code = narrative_cli(arguments, provider_factory=lambda *_args, **_kwargs: provider)
    if code != 0:
        raise RuntimeError(f"offline walkthrough stopped with CLI exit {code}")


def run_demo(destination: Path) -> None:
    """Create a new output directory; never replace an earlier walkthrough."""
    destination.mkdir(parents=True, exist_ok=False)
    workflow = Path(__file__).parent / "workflows" / "game-quest-production.json"
    baseline, edited, branch = (
        destination / name for name in ("baseline.json", "edited.json", "branch.json")
    )
    provider = FixtureProvider(
        (
            "One keeper, one player, no combat; the brass bell is reusable.",
            "Borrow the bell, signal, then return to the keeper.",
            "Keeper: Ring the bell to warn the harbor. Player: I will try.",
            "The first draft has no recovery path for a failed signal.",
            BASELINE,
        )
    )
    _cli(
        (
            "generate",
            "--workflow",
            str(workflow),
            "--prompt",
            BRIEF,
            "--artifacts",
            str(baseline),
            "--output",
            str(destination / "baseline.md"),
            "--max-calls",
            "5",
            "--max-total-output-tokens",
            "7600",
        ),
        provider,
    )

    data = load_run_bundle(baseline).to_dict()
    data["stages"][3]["content"] = CORRECTION
    edited.write_text(dumps_run_bundle(loads_run_bundle(json.dumps(data))), encoding="utf-8")
    resumed_provider = FixtureProvider((REVISED,), required_context=CORRECTION)
    _cli(
        (
            "resume",
            "--artifacts-in",
            str(edited),
            "--from-stage",
            "handoff",
            "--artifacts-out",
            str(branch),
            "--output",
            str(destination / "branch.md"),
            "--max-calls",
            "1",
            "--max-total-output-tokens",
            "1800",
        ),
        resumed_provider,
    )
    if (provider.calls, resumed_provider.calls) != (5, 1):
        raise RuntimeError("unexpected generate/resume call counts")

    manifest = EvaluationManifest(
        evaluation_id="offline-harbor-demo",
        title="OFFLINE FIXTURE — Harbor review wiring",
        seed="reproducible-demo-seed",
        rubric=(RubricCriterion("recovery", "Failure recovery", "Is a retry path specified?"),),
        cases=(
            EvaluationCase(
                "harbor",
                (
                    EvaluationTreatment("baseline", "baseline.json"),
                    EvaluationTreatment("human-edit", "branch.json"),
                ),
            ),
        ),
    )
    manifest_path = destination / "manifest.json"
    manifest_path.write_text(json.dumps(manifest.to_dict(), indent=2), encoding="utf-8")
    key, scores = destination / "private-key.json", destination / "scores.json"
    _cli(
        (
            "evaluate",
            "prepare",
            "--manifest",
            str(manifest_path),
            "--packet",
            str(destination / "packet.md"),
            "--key",
            str(key),
            "--scores",
            str(scores),
        )
    )
    # Leave the blank score sheet untouched for a real reviewer. These neutral sample
    # scores only verify report plumbing; they are not an assessment of either draft.
    sample = json.loads(scores.read_text(encoding="utf-8"))
    sample["reviewer"] = "SYNTHETIC-WIRING-CHECK-NOT-HUMAN"
    for case in sample["cases"]:
        case["ratings"] = {label: {"recovery": 3} for label in ("A", "B")}
        case["preference"] = "tie"
        case["notes"] = "Synthetic neutral scores for wiring only; no quality conclusion."
    sample_scores = destination / "sample-scores.json"
    sample_scores.write_text(json.dumps(sample, indent=2), encoding="utf-8")
    _cli(
        (
            "evaluate",
            "report",
            "--key",
            str(key),
            "--scores",
            str(sample_scores),
            "--output",
            str(destination / "sample-report.md"),
            "--json-output",
            str(destination / "sample-report.json"),
        )
    )
    print(f"Offline walkthrough saved to {destination.resolve()}")
    print("5 initial fixture calls + 1 resumed fixture call; no network or model tokens.")
    print("Read branch.md and packet.md. Sample scores are synthetic, not quality evidence.")
    print(
        "For real review share only packet.md and blank scores.json; keep all other files private."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True, help="new directory to create")
    args = parser.parse_args()
    try:
        run_demo(args.output_dir)
    except FileExistsError:
        parser.exit(2, "Output directory already exists; choose a new directory to preserve it.\n")


if __name__ == "__main__":
    main()
